### ISSUE TITLE
[Feature]: Displaying the value on the Bar

### ISSUE THREAD

**Issue by pushkar-2804** [tremorlabs/tremor-raw#104]
### What problem does this feature solve?

Displaying the value directly on the bars of a chart solves several usability and communication problems, such as:

- Enhanced Data Visibility: It makes the exact data values immediately visible without requiring the user to hover over the bars, click, or look at an external legend or data table.

- Improved Accessibility: For users with limited dexterity or on devices where hover or precise selection is difficult, showing the values on the chart directly ensures they still receive the necessary information.

- Faster Interpretation: Users can quickly compare values across bars without additional actions or cognitive load, making it easier to identify trends, outliers, or differences.

- Self-Contained Presentation: For printed reports, static images, or embedded charts, the values on the bars make the chart more informative and self-explanatory without requiring additional context.

- Better Design for Dynamic Data: When values are displayed directly, it supports dynamic charts where data changes frequently, reducing the need to update additional external labels or legends.

### What does the proposed API look like?

# New Prop:
<b>showValues (boolean):</b>
A flag to enable or disable displaying the formatted values on the bars. Default: false.

![image](https://github.com/user-attachments/assets/d76a67d9-d853-4797-a305-c571c0346f08)

``` 
import { BarChart } from "@tremor/react";

const data = [
  { month: "Jan", revenue: 4500 },
  { month: "Feb", revenue: 5000 },
  { month: "Mar", revenue: 7000 },
];

const valueFormatter = (value: number) => `$${value.toLocaleString()}`;

const App = () => (
  <BarChart
    data={data}
    index="month"
    categories={["revenue"]}
    showValues={true} // Enables value display on bars
    valueFormatter={valueFormatter} // Formats the displayed values
    colors={["blue"]}
  />
);

export default App;
```
## Why This Approach?
- Keeps the API Minimal: No duplication or unnecessary new props.
- Leverages Existing Functionality: Uses the already implemented valueFormatter for consistency.
- Backwards Compatible: Adds the showValues feature without affecting the current behavior.

**Comment by severinlandolt** [comment]
Hi! This feature has been requested multiple times and I have to reject it. Labels are too unpredictable in terms of size, length of the text and in terms of overlap, bar, line or area width. Thus we reject this proposal.

In case you want add a label yourself, you could add this to the props of the chart

```tsx
// import { ImplicitLabelType } from "recharts/types/component/Label";

renderLabel,

```

And adjust the coresponding `Bar`, `Area`, or `Line` component with ` label={renderLabel}`.

So you can now add any custom label you want like: 
```tsx
renderLabel={{ fill: "white", fontSize: 20, position: "top" }}
```
