### ISSUE TITLE
How do I update already updated components?

### ISSUE THREAD

**Issue by ynishimura** [tremorlabs/tremor-raw#57]
I've recently started using tremor-raw.

I love its modern implementation and clean design.

I'm building a dashboard based on this repository:
https://github.com/tremorlabs/template-dashboard-oss

I would like to keep it up-to-date with the daily updates. What's the best way to do this?

**Comment by severinlandolt** [comment]
Hi! If there are any significant updates to our templates, we add them to the blocks changelog: https://blocks.tremor.so/changelog

**Comment by ynishimura** [comment]
Thanks for the reply!
Is the only way to update the tremor-raw file by copying and pasting?
If I customize it a bit, is the only way to understand and modify the differences?

**Comment by severinlandolt** [comment]
Yes, this is correct
