### ISSUE TITLE
[Bug]: Tracker component hover issue

### ISSUE THREAD

**Issue by hatemachine007** [tremorlabs/tremor-raw#59]
### Tremor Raw Component Version

must be v0.1.1

### Link to minimal reproduction

https://raw.tremor.so/docs/visualizations/tracker

### Steps to reproduce

step 1: go to https://raw.tremor.so/docs/visualizations/tracker
step 2: on the small bar in the preview section move your mouse from left to right or right to left as fast as possible 
step 3: you might notice the UI issue on the small bar

PFA
![image](https://github.com/user-attachments/assets/e35d0f60-5002-4e15-8cde-87a1151ce7e7)

### What is expected?

The hover on the bar should show the proper value

### What is actually happening?

It is showing some issues with the UI you can refer to the screenshot attached

### What browsers are you seeing the problem on?

Chrome

**Comment by severinlandolt** [comment]
@hatemachine007 Having a hard time replicating this issue, but also heard it not for the first time. Just updated Radix ui. Could you check it again? Thanks!

**Comment by hatemachine007** [comment]
Hi @severinlandolt, I still see the issue. Even I checked in the private window.

![image](https://github.com/user-attachments/assets/b7a0dc9f-2c1b-4ee8-b3ef-70da80ec5ebb)

**Comment by severinlandolt** [comment]
Hi @hatemachine007, I am using the latest Chrome version 128.0.6613.86. Do you still have this issue?
