### ISSUE TITLE
[Bug]: Missing Active Dot on Hover

### ISSUE THREAD

**Issue by michaelhvisser** [tremorlabs/tremor-raw#61]
### Tremor Raw Component Version

Tremor Raw AreaChart [v0.3.0]

### Link to minimal reproduction

n/a

### Steps to reproduce

Followed the steps to add Tremor Raw into my Next.js project and added the default area chart component.

### What is expected?

When hovering on the chart the active dot should show. 

### What is actually happening?

![Screenshot 2024-07-16 at 3 16 19 PM](https://github.com/user-attachments/assets/6f37d8a7-e294-43cc-9b11-6c79dd462c14)

On hover there is no active dot. When you inspect the browser it shows the fill as transparent.

**Comment by MrLepage** [comment]
@michaelhvisser 
What was the issue?

**Comment by michaelhvisser** [comment]
I'm using shadcn UI as the component library for aspects of the code. Their utility function for merging tailwind classes is CN vs your which uses CX (if I'm remembering correctly) I did a find an replace as to not need to have two functions that did the same thing in my code base. As a result it replaced needed code that broke the recharts piece. Totally my fault.

**Comment by MrLepage** [comment]
Thank you! 
I just made the same mistake while refactoring...

**Comment by michaelhvisser** [comment]
I love the functionality of your charts. The new shadcn/ui stuff allows for a rounded shape to the charts. When I attempted to update your shape to allow for a rounded corner. I found that you were managing this in a separate function. Do you have have any thoughts about making the styling of bar charts a bit easier? If you us the standard Recharts API directly you can apply the style to each bar. Your charts are amazing cause you get a lot of additional features for free. Any thoughts on allowing the user to easier style the raw charts?
