### ISSUE TITLE
[Bug]: Progress Circle importing cx from ./utils

### ISSUE THREAD

**Issue by imbatman** [tremorlabs/tremor-raw#66]
### Tremor Raw Component Version

Tremor Raw ProgressCircle [v0.0.0]

### Link to minimal reproduction

https://raw.tremor.so/docs/visualizations/progress-circle

### Steps to reproduce

Notice the cx import is from `./utils` which causes a cannot find module error.

### What is expected?

The import of cx should be `import { cx } from "@/lib/utils"`

### What is actually happening?

The import is `import { cx } from "./utils"`

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by severinlandolt** [comment]
Thanks, should be fixed now!
