### ISSUE TITLE
[Bug]: Install Dependencies (Optional) doesn't include @radix-ui/react-dropdown-menu

### ISSUE THREAD

**Issue by imbatman** [tremorlabs/tremor-raw#67]
### Tremor Raw Component Version

Installation

### Link to minimal reproduction

https://raw.tremor.so/docs/getting-started/installation/next#install-dependencies

### Steps to reproduce

On the (Optional) Installation steps on
https://raw.tremor.so/docs/getting-started/installation/next#install-dependencies
https://raw.tremor.so/docs/getting-started/installation/vite#install-dependencies
https://raw.tremor.so/docs/getting-started/installation/remix#install-dependencies

The `npm install` command does not include `@radix-ui/react-dropdown-menu`

### What is expected?

The command should include `@radix-ui/react-dropdown-menu`

### What is actually happening?

This causes issues when creating the Dropdown Menu component as `import * as DropdownMenuPrimitives from "@radix-ui/react-dropdown-menu";` is not available

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by severinlandolt** [comment]
Thanks for the heads up, fixed!
