### ISSUE TITLE
[Bug]: Visible Scrollbars in DateRangePicker when system settings are set to always show scroll bars

### ISSUE THREAD

**Issue by jnsdrssn** [tremorlabs/tremor-raw#72]
### Tremor Raw Component Version

Tremor Raw Date Picker [v1.0.3]

### Link to minimal reproduction

don't have time i'm sorry

### Steps to reproduce

On macOS go to System Settings -> Appearance, Select "Always" in menu "Show scroll bars".

### What is expected?

Scroll bars are invisible when content doesn't overflow

### What is actually happening?

Scroll bars are visible but content doesn't overflow
<img width="630" alt="Screenshot 2024-08-28 at 13 45 59" src="https://github.com/user-attachments/assets/c66a0c9f-4164-4f45-b3a1-7c4db857382a">

**Comment by jnsdrssn** [comment]
the fix is to use `overflow-auto` instead of  `overflow-scroll` btw

**Comment by severinlandolt** [comment]
Hi @jnsdrssn, I vaguely remember that there was a reason why I made the scroll behaviour explicit. I will take a look at it today. 🤔
