### ISSUE TITLE
[Feature]: (Charts) Enable category selection interactivity regardless of onValueChange

### ISSUE THREAD

**Issue by MrLepage** [tremorlabs/tremor-raw#78]
#### Description

Currently, the ability to select a category (by clicking on a line) is disabled if the `onValueChange` prop is not provided. This limits the functionality of the chart, as users might want to focus on a specific line even if there's no external state management through `onValueChange`.

#### Current Behavior

The interactivity for selecting a category (line) is only enabled when the `onValueChange` prop is provided.

#### Proposed Behavior

Allow category selection interactivity regardless of whether `onValueChange` is provided. This would enable users to focus on a specific line for visual emphasis, even without external state management.

#### Suggested Implementation

Remove the conditional rendering based on `onValueChange`.

#### Benefits

- Improved user experience by allowing focus on specific lines
- More flexible chart behavior, not dependent on external state management
- Consistent interactivity across different use cases

#### Questions

- Should we consider adding a prop to explicitly enable/disable this feature?
- Are there any performance considerations for larger datasets? Currently, we're adding an additional invisible line for each category to improve clickability. For larger datasets with many categories, this approach doubles the number of `<Line>` components rendered, which could potentially impact performance.
  
#### Additional Context

This change would make the chart more interactive and user-friendly in scenarios where external state management isn't needed or desired.

**Comment by severinlandolt** [comment]
Hi @MrLepage, let's consider a scenario where we add a new prop, enableInteractivity. What should happen if onValueChange is provided but interactivity is disabled? Should one setting override the other, or should we throw a warning in the console?

The simplest approach is to pass `onValueChange={() => {}}`. The user wouldn’t notice, and we avoid adding an extra prop or dealing with the potential conflict mentioned above.
