### ISSUE TITLE
[Feature]: Add month and year jump in Date Picker

### ISSUE THREAD

**Issue by ptk-dev** [tremorlabs/tremor-raw#79]
### What problem does this feature solve?

Currently it's much hard to pick dates wi=ich are few years back, adding year and month jump would make it easier and accessible to pick dates from. Example how's the jump may would work is below.
![download](https://github.com/user-attachments/assets/7d146215-edfc-44a2-a7f1-7f5639634e96)

**Comment by severinlandolt** [comment]
Hey there! We dont want to overload the datepicker, it's already quite large.

However, I created a new examples with with select menus for year and month: https://tremor.so/docs/inputs/date-picker#example-custom-birth-date-picker

Happy coding :)
