### ISSUE TITLE
[Deprecation] Custom state pseudo classes have been changed from ":--webkit-search-cancel-button" to ":state(webkit-search-cancel-button)". See more here: https://github.com/w3c/csswg-drafts/issues/4805

### ISSUE THREAD

**Issue by alissa-tung** [tremorlabs/tremor-raw#81]
https://github.com/tremorlabs/tremor-raw/blob/982b88d47776810532163519a41f7c7cac8a1625/src/components/Input/Input.tsx#L39

I am new to Web development, I am not sure why `[&::--webkit-search-cancel-button]:hidden` is used. Seems that remove this can eliminate this error

**Comment by severinlandolt** [comment]
Hi! This is because we want to hide the "X" button in the input filed with type="search" in Safari. Without this, the input looks like this: 
![CleanShot 2024-09-05 at 17 57 08@2x](https://github.com/user-attachments/assets/2941c4fb-2f55-43b9-9f02-283580941386)

**Comment by alissa-tung** [comment]
> [&::-webkit-search-cancel-button]:hidden

I have only test it on Chrome, the remain `[&::-webkit-search-cancel-button]:hidden` cause no error and no cancel button. Is double dash one need by another browser?

**Comment by severinlandolt** [comment]
Ah, now I understand 💡 You are right, this is a mistake. Fill fix it asap.
